language: node_js

node_js:
  - "6.10"
  - "lts/*"

env:
  global:
    secure: uBk0tfk+afx0XG6ojbfmL8+tExgyFV5unAk5dErO3YeXUOhaniRErl9l/TBfA6E0LddpMphQ3ZZNQCNTA8K9H2N0HdfU4LLI1NOdnNNOpVw/F270NRyvWHsr0y+iQ++hfNdj9pO6zJq6T7b//okJuWWII3e7cwUbuYeWw95q2pK4gll1bU8E6ydRCCfC8nnBMVYdNYIgqS8PK3pXd2XLBPVrNP2iuKV65XUHrk4bOwk0ZLZYdWruN84Evs9qXgMS9VXaQ6+S8oj2urudBmDzuRws4v4aH+3uPOadUUgie22aMEgOfOGTm+WfUkr01BOaeRBj1odNR2IIyPq+B4xH7zdtdCu7Ncstf9KrweFHkV4PFmaorK3Dur7iVMHjzSz0rDiM7uEn992ocbSDwiKfkzk0pvZLo6PzjtAZay/NwUPFCfqjdZfaMbpbMiPoJ+OJSbRX6OjO0EkBlslVXDDH1EWJAQ4NdUXp0YL5Yc5zXFM7j897GrDGK3gXSH23flBthvFCJuuNGGIY+5Ak4K9kZvCIOAtu1ToRgig/NYEt9nEtZiHkiZL2N0jvN206Xzet5mITtWFJhQP6aDJ6JssLDheUY1JLaBCC0MeC+RDXaBIVt+hcH4kez2MIPBqZcN1AU4fs9NEajFf7ZAz36VskHknXgOOLno5OmyghMTVRFuo=
    - PERCY_ENABLE=0

matrix:
  include:
    - node_js: "11"
      env: DEPLOY=run

addons:
  chrome: stable

cache:
  directories:
    - "node_modules"

before_script:
  - if [[ $TRAVIS_PULL_REQUEST != 'false' ]] && [[ $DEPLOY = 'run' ]]; then echo "Percy Enabled" && export PERCY_ENABLE=1; fi
  - echo $PERCY_ENABLE

script:
  - npm run build
  - npm run lint
  - npm start &
  - npm test

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    local_dir: docs
    on:
      branch: master
      condition: "$DEPLOY = run"

  - provider: npm
    skip_cleanup: true
    email: "web-tech+npm@20minutes.fr"
    api_key:
      # This is the NPM token finishing by e8f7
      secure: "AuyoDlLWUnaOAeXJHeawfteCHyKj3imdNel+Lha+3gQQyq47veMC+J0dbzZ3I8kLGIr6kI8y1xrK4pVFXjHQXlq5Kh0+oIUUPL/DpmljVeIFslVjde9Xt9pgZTZgbUXv3zTIq2gLMW4KC4efYkWpnpmT6TruV6Ym/3AZCinWv7rtKkPhbvlTxhnQRNaWur+BrFWQ1F4YTrod5UMl7KtevXCLqTby5oJ3QmZLNxmGZBoKUnrEWL4Gcf7hK/JYvtPszjPkeUaHW8tPmakmHnpvjm4Pnm/2ackS8Z3Izue2a6Hre7VPjVO35HXSEzwApXoXGfivJ6fXK1Ifd4Uv3aiJ3iwD2u0ACtrQEaorzGJKvEjAWNxYGLsTyCoMvpR3g86EWNtEb8HbWHZl7adhp5iHwbRMJYYifx1j7p3aEg/eMtINVLHzS3+6SRQS1YHyM2jRF6nPl1LnjZSz5Ex+TLyEq9JHgl6kBBOJMg+EACeGMN2m5GRre4kbDa/b6SAslEmVLjAbMeFJGYOBU2QOEu5J7kzyIWilQp830yQrlM7EBM6j7B7ZjPH6ZVNpiZJesWJbvZ/dWTY+nUmUozupybuFjqoJTcQHYPFZRBHcvdhCR93J462aQt030rhoOLd9OQd5XI+gwfp0d8vJameYQ0rTyCXA6Uaf1z7igke6a5mTqt4="
    on:
      tags: true
      condition: "$DEPLOY = run"
