language: node_js

node_js:
  - "4"
  - "lts/*"

matrix:
  include:
    - node_js: "stable"
      env: DEPLOY=run

cache:
  directories:
    - "node_modules"

script:
  - gulp build
  - gulp docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs
  on:
    branch: master
    condition: $DEPLOY = run
